import {
    RadioGroupBlock,
    ParagraphBlock,
    InputTypes,
    ButtonBlock,
    HeadingBlock,
    TextBolck,
    DropdownBlock,
    DatePicker,
    Checkbox,
    ImageUploadBlock,
    RatingBlock,
    FileUploadBlock,
} from "../components/FromBuilder/Preview";

export const BLOCK_COMPONENT_MAP: Record<string, any> = {
    text: InputTypes,
    email: InputTypes,
    phone: InputTypes,
    number: InputTypes,
    password: InputTypes,
    url: InputTypes,
    paragraph: ParagraphBlock,
    heading: HeadingBlock,
    textarea: TextBolck,
    dropdown: DropdownBlock,
    date: DatePicker,
    checkbox: Checkbox,
    image: ImageUploadBlock,
    rating: RatingBlock,
    button: ButtonBlock,
    file: FileUploadBlock,
    radio: RadioGroupBlock,
};
